Resolved issues in authorization when going trough pages using naviga…
yksop/Ingegneria_Del_Software pull request #28
Opened 2024-05-21 16:31 UTC by kikalore

- Resolved issues in authorization when going through pages using navigation bar. 
- Add authorizations control on backend for my user stories.
-  Error displaying implemented on the frontend for my user stories.

2024-05-21 16:37 UTC, yksop requested changes

2024-05-21 16:37 UTC, yksop commented on backend/app/routes/AlertController.js
> +    const authHeader = req.headers.authorization;
tutta sta roba è meglio metterla in un middleware e richiamarla quando serve. guarda come ho fatto nella mia pr

2024-05-21 16:37 UTC, yksop commented on frontend/src/router/index.js
> +      if (!token) {
perchè due if uguali?

2024-05-21 18:20 UTC, kikalore commented on backend/app/routes/AlertController.js
> +    const authHeader = req.headers.authorization;
ok

2024-05-22 07:53 UTC, AlbertoDB20 commented on backend/app/routes/AlertController.js
> +    const authHeader = req.headers.authorization;
Concordo fede, hai messo codice ripetuto che diminuisce la leggibilità e che, a quanto ho letto in Internet, è meglio gestirlo con un middleware. 
Ti lascio qui qualche link che mi è stato utile per capire sto passaggio:
- https://auth0.com/learn/token-based-authentication-made-easy
- https://www.digitalocean.com/community/tutorials/nodejs-jwt-expressjs
- https://www.digitalocean.com/community/tutorials/nodejs-creating-your-own-express-middleware

Questi due ultimi, parlano proprio del middleware come strumento "filtro" che previene azione indesiderate da parte di utenti senza i requisiti o non loggati. 
Dacci un occhio che son fatti bene.

2024-05-22 11:00 UTC, yksop approved these changes

2024-05-22 11:13 UTC, merged