Add Retire Alert endpoint
yksop/Ingegneria_Del_Software pull request #7
Opened 2024-05-04 20:44 UTC by yksop

2024-05-04 20:45 UTC, yksop commented on app/models/Alert
> -  "traumacranico",
la fede puzza

2024-05-05 07:11 UTC, AlbertoDB20 commented on app/routes/UserController.js
Posky ma tu avevi fatto il pull dalla Develop? 
Al di là del fatto che mi hai corretto solo spaziature e cose ininfluenti, questo codice del log-in non è allineato con quello in develop...

2024-05-05 07:12 UTC, AlbertoDB20 commented on app/routes/UserController.js
> +const EXPIRAL_AUTH_TIME = "2 days";
che cosa cambia???

2024-05-05 07:30 UTC, AlbertoDB20 requested changes
secondo me non applicare modifiche al codice degli altri perché nel mio caso, essendo codice parziale, poi ci potrebbero essere problemi di merging. 
In caso contrario fammi sapere e ritiro il Request changes

2024-05-05 14:13 UTC, AlbertoDB20 approved these changes

2024-05-05 14:13 UTC, merged